import type { CommandDefinition } from '../schemas/commandSchemas'

export const commandRegistry: CommandDefinition[] = [
  {
    category: 'Navigate',
    description: 'Open the executive operational overview.',
    icon: 'overview',
    id: 'navigate-overview',
    keywords: ['dashboard', 'home', 'kpi'],
    label: 'Go to overview',
    permission: 'dashboard.view',
    to: '/overview',
  },
  {
    category: 'Navigate',
    description: 'Explore operational trends and distributions.',
    feature: 'analytics',
    icon: 'analytics',
    id: 'navigate-analytics',
    keywords: ['metrics', 'trends', 'charts'],
    label: 'Go to analytics',
    permission: 'analytics.view',
    to: '/analytics',
  },
  {
    category: 'Navigate',
    description: 'Open assigned and department operational work.',
    icon: 'task',
    id: 'navigate-tasks',
    keywords: ['work', 'queue', 'board'],
    label: 'Go to tasks',
    permission: 'tasks.view',
    to: '/tasks',
  },
  {
    category: 'Create',
    description: 'Create and assign a new operational task.',
    icon: 'task',
    id: 'create-task',
    keywords: ['add', 'new', 'work'],
    label: 'Create task',
    permission: 'tasks.manage',
    to: '/tasks/new',
  },
  {
    category: 'Navigate',
    description: 'Review assigned and submitted decisions.',
    icon: 'approval',
    id: 'navigate-approvals',
    keywords: ['review', 'decision', 'request'],
    label: 'Go to approvals',
    permission: 'approvals.review',
    to: '/approvals',
  },
  {
    category: 'Create',
    description: 'Submit a governed request for approval.',
    icon: 'approval',
    id: 'create-approval',
    keywords: ['new', 'request', 'decision'],
    label: 'Create approval request',
    permission: 'approvals.review',
    to: '/approvals/new',
  },
  {
    category: 'Navigate',
    description: 'Browse governed process definitions.',
    icon: 'workflow',
    id: 'navigate-workflows',
    keywords: ['process', 'state', 'transition'],
    label: 'Go to workflows',
    permission: 'workflows.view',
    to: '/workflows',
  },
  {
    category: 'Create',
    description: 'Design a new versioned workflow definition.',
    icon: 'workflow',
    id: 'create-workflow',
    keywords: ['new', 'process', 'designer'],
    label: 'Create workflow',
    permission: 'workflows.manage',
    to: '/workflows/new',
  },
  {
    category: 'Navigate',
    description: 'Execute and manage saved operational reports.',
    icon: 'report',
    id: 'navigate-reports',
    keywords: ['business intelligence', 'export', 'table'],
    label: 'Go to reports',
    permission: 'reports.view',
    to: '/reports',
  },
  {
    category: 'Create',
    description: 'Configure a reusable operational report.',
    icon: 'report',
    id: 'create-report',
    keywords: ['new', 'builder', 'export'],
    label: 'Create report',
    permission: 'reports.manage',
    to: '/reports/new',
  },
  {
    category: 'Navigate',
    description: 'Browse controlled files and immutable versions.',
    feature: 'documents',
    icon: 'document',
    id: 'navigate-documents',
    keywords: ['files', 'attachments', 'versions'],
    label: 'Go to documents',
    permission: 'documents.view',
    to: '/documents',
  },
  {
    category: 'Create',
    description: 'Register a new controlled document.',
    feature: 'documents',
    icon: 'document',
    id: 'create-document',
    keywords: ['upload', 'file', 'attachment'],
    label: 'Add document',
    permission: 'documents.manage',
    to: '/documents/new',
  },
  {
    category: 'Navigate',
    description: 'Manage organization structure and ownership.',
    icon: 'department',
    id: 'navigate-departments',
    keywords: ['organization', 'unit', 'owner'],
    label: 'Go to departments',
    permission: 'departments.view',
    to: '/departments',
  },
  {
    category: 'Create',
    description: 'Add an accountable organization unit.',
    icon: 'department',
    id: 'create-department',
    keywords: ['new', 'organization', 'unit'],
    label: 'Create department',
    permission: 'departments.manage',
    to: '/departments/new',
  },
  {
    category: 'Navigate',
    description: 'Browse managed workforce identities.',
    icon: 'user',
    id: 'navigate-users',
    keywords: ['people', 'identity', 'directory'],
    label: 'Go to users',
    permission: 'users.view',
    to: '/users',
  },
  {
    category: 'Create',
    description: 'Add a managed workforce identity.',
    icon: 'user',
    id: 'create-user',
    keywords: ['new', 'person', 'identity'],
    label: 'Create user',
    permission: 'users.manage',
    to: '/users/new',
  },
  {
    category: 'Navigate',
    description: 'Review roles, permissions, and assignments.',
    icon: 'security',
    id: 'navigate-access',
    keywords: ['roles', 'permissions', 'rbac'],
    label: 'Go to access control',
    permission: 'security.manage',
    to: '/access',
  },
  {
    category: 'Navigate',
    description: 'Inspect immutable cross-domain change records.',
    icon: 'audit',
    id: 'navigate-audit',
    keywords: ['history', 'trace', 'changes'],
    label: 'Go to audit trail',
    permission: 'audit.view',
    to: '/audit',
  },
  {
    category: 'Navigate',
    description: 'Manage workspace preferences and platform policy.',
    icon: 'settings',
    id: 'navigate-settings',
    keywords: ['preferences', 'configuration', 'policy'],
    label: 'Go to settings',
    permission: 'settings.view',
    to: '/settings',
  },
  {
    category: 'Search',
    description: 'Open the full cross-entity search workspace.',
    icon: 'search',
    id: 'navigate-search',
    keywords: ['find', 'discover', 'saved searches'],
    label: 'Open global search',
    to: '/search',
  },
]
